name: Net Check CI

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Choose CI execution mode'
        required: true
        default: 'bash'
        type: choice
        options:
          - bash
          - ansible
          - docker

jobs:
  run-ci:
    name: Run ${{ github.event.inputs.mode }} CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python (if needed)
        if: ${{ github.event.inputs.mode != 'docker' }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible (only for ansible mode)
        if: ${{ github.event.inputs.mode == 'ansible' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Bash Scripts
        if: ${{ github.event.inputs.mode == 'bash' }}
        run: ./run_tests.sh

      - name: Run Ansible Playbook
        if: ${{ github.event.inputs.mode == 'ansible' }}
        run: |
          ansible-playbook ansible/run_scripts.yml -i localhost, -c local

      - name: Build and Run Docker container
        if: ${{ github.event.inputs.mode == 'docker' }}
        run: |
          docker build -t net-check-scripts .
          docker run --rm net-check-scripts
